apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-push-to-registry-redhat-iotest-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-push-to-registry-redhat-iotest-component
    app.kubernetes.io/part-of: rh-push-to-registry-redhat-iotest
  name: rh-push-to-registry-redhat-iotest-component
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: rh-push-to-registry-redhat-iotest-component
status:
  loadBalancer: {}
